/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Component;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.Parent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.DBModel;
import model.IModel;

/**
 *
 * @author user
 */
public class MainWindow extends javax.swing.JFrame {

  private IModel model;
  
  
    public MainWindow() {
        String jdbcURL = "jdbc:mysql://localhost:3306/megrendelesek";
        String dbUser = "root";
        String dbPass = "1234";
        
      try {
          Connection conn = DriverManager.getConnection(jdbcURL, dbUser,dbPass);
          model=new DBModel(conn);
      } catch (SQLException ex) {
          HibaAblak(this, ex.toString());
      }
        
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Order Handling Application 1.02");
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                sajatClose();
            }
            
});
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public static void HibaAblak(Component  parent,String hiba ){
         JOptionPane.showMessageDialog(parent, hiba,"Error!", JOptionPane.ERROR_MESSAGE);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miKilepes = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenu();
        miSzemelyek = new javax.swing.JMenuItem();
        miMegrendelesek = new javax.swing.JMenuItem();
        miExport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Exit");

        miKilepes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        miKilepes.setText("Exit");
        miKilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKilepesActionPerformed(evt);
            }
        });
        jMenu1.add(miKilepes);

        menu.add(jMenu1);

        menu2.setText("Data");

        miSzemelyek.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miSzemelyek.setText("Costumers");
        miSzemelyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSzemelyekActionPerformed(evt);
            }
        });
        menu2.add(miSzemelyek);

        miMegrendelesek.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        miMegrendelesek.setText("Orders");
        miMegrendelesek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMegrendelesekActionPerformed(evt);
            }
        });
        menu2.add(miMegrendelesek);

        miExport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        miExport.setText("Export");
        miExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExportActionPerformed(evt);
            }
        });
        menu2.add(miExport);

        menu.add(menu2);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExportActionPerformed
     JFileChooser fc = new JFileChooser();
     int valasz=fc.showSaveDialog(this);
     if(valasz==JFileChooser.APPROVE_OPTION){
         File file=fc.getSelectedFile();
         try {
             model.exportToFile(file);
             JOptionPane.showMessageDialog(rootPane, "The data succsessfully saved to file to here:"+file.getAbsolutePath(), "Done!",JOptionPane.INFORMATION_MESSAGE );
         } catch (Exception ex) {
             MainWindow.HibaAblak(menu, ex.toString());
         }
     }
     
    }//GEN-LAST:event_miExportActionPerformed
public void  sajatClose (){
      try {
          if (model!=null){
          model.close();}
      } catch (SQLException ex) {
          HibaAblak(this, ex.toString());
      }
       System.exit(0);
}
    private void miKilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKilepesActionPerformed
       
        sajatClose();
       
    }//GEN-LAST:event_miKilepesActionPerformed

    private void miSzemelyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSzemelyekActionPerformed
       SzemelyekDialog szd = new SzemelyekDialog(this, true, model);
       szd.setVisible(true);
       
    }//GEN-LAST:event_miSzemelyekActionPerformed

    private void miMegrendelesekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMegrendelesekActionPerformed
        MegrendelesekDialog md =new MegrendelesekDialog(this,model);
        md.setVisible(true);
               
        
    }//GEN-LAST:event_miMegrendelesekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menu2;
    private javax.swing.JMenuItem miExport;
    private javax.swing.JMenuItem miKilepes;
    private javax.swing.JMenuItem miMegrendelesek;
    private javax.swing.JMenuItem miSzemelyek;
    // End of variables declaration//GEN-END:variables
}
