/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import model.Szemely;

/**
 *
 * @author user
 */
public class SzemelyAdatokDialog extends javax.swing.JDialog {

  
           private Szemely szemely;
           private boolean mentes;
           
    public SzemelyAdatokDialog(java.awt.Frame parent,Szemely szemely) {
        super(parent, true);
        initComponents();
       
        setLocationRelativeTo(parent);
        mentes=false;
        this.szemely=szemely;
        
        if(szemely==null){
             setTitle("Új személy létrehozása");
        }
        else{
             setTitle("Új személy módosítása");
             tfNev.setText(szemely.getNev());
             tfEmail.setText(szemely.getEmail());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNev = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        btMegsem = new javax.swing.JButton();
        btMentes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("E-mail");

        tfNev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNevKeyReleased(evt);
            }
        });

        tfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEmailKeyReleased(evt);
            }
        });

        btMegsem.setText("Cancel");
        btMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMegsemActionPerformed(evt);
            }
        });

        btMentes.setText("Save");
        btMentes.setEnabled(false);
        btMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btMentes)
                        .addGap(42, 42, 42)
                        .addComponent(btMegsem))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                        .addComponent(tfNev)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMentes)
                    .addComponent(btMegsem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfEmail, tfNev});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMentesActionPerformed

        if(szemely==null){
            szemely=new Szemely();
        }
        szemely.setNev(tfNev.getText());
        szemely.setEmail(tfEmail.getText());
       
        mentes=true;
        setVisible(false);
    }//GEN-LAST:event_btMentesActionPerformed

    private void btMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMegsemActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btMegsemActionPerformed

    private void tfNevKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNevKeyReleased
        hosszellenoriz();
    }//GEN-LAST:event_tfNevKeyReleased

    private void tfEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmailKeyReleased
         hosszellenoriz();
    }//GEN-LAST:event_tfEmailKeyReleased
private void  hosszellenoriz(){
    if(tfNev.getText().length()>=3&&tfEmail.getText().length()>=3){
        btMentes.setEnabled(true);
    }else{
        btMentes.setEnabled(false);
    }
}
    /**
     * @param args the command line arguments
     */

    /**
     * @param args the command line arguments
     */
    public boolean isMentes() {
        return mentes;
    }

    public Szemely getSzemely() {
        return szemely;
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMegsem;
    private javax.swing.JButton btMentes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNev;
    // End of variables declaration//GEN-END:variables
}
