/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Frame;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.IModel;
import model.Szemely;


/**
 *
 * @author user
 */
public class SzemelyekDialog extends javax.swing.JDialog {

  private IModel model;
  private Frame parent;
  private List <Szemely> szemelyek;
   
    public SzemelyekDialog(java.awt.Frame parent, boolean modal, IModel model) {
        super(parent, modal);
        this.model=model;
        this.parent=parent;
        initComponents();
        
        setLocationRelativeTo(parent);
        
     listafrissit();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listlSzemelyek = new javax.swing.JList();
        btUj = new javax.swing.JButton();
        btModosit = new javax.swing.JButton();
        btTorol = new javax.swing.JButton();
        btOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listlSzemelyek.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listlSzemelyek);

        btUj.setText("New");
        btUj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUjActionPerformed(evt);
            }
        });

        btModosit.setText("Edit");
        btModosit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModositActionPerformed(evt);
            }
        });

        btTorol.setText("Delete");
        btTorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTorolActionPerformed(evt);
            }
        });

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btModosit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btTorol, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btUj, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btOk, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btModosit, btOk, btTorol, btUj});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btUj)
                        .addGap(18, 18, 18)
                        .addComponent(btModosit)
                        .addGap(18, 18, 18)
                        .addComponent(btTorol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(btOk))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUjActionPerformed
       SzemelyAdatokDialog szad = new SzemelyAdatokDialog(parent,null);
       szad.setVisible(true);
       if(szad.isMentes()){
           Szemely menteni = szad.getSzemely();
           try {
               model.addSzemely(menteni);
               listafrissit(); 
           } catch (SQLException ex) {
              MainWindow.HibaAblak(parent, ex.toString());
           }
       }
    }//GEN-LAST:event_btUjActionPerformed

    private void btModositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModositActionPerformed
      Szemely kivalasztott= (Szemely) listlSzemelyek.getSelectedValue();
        
      if(kivalasztott!=null){
          

        SzemelyAdatokDialog szad = new SzemelyAdatokDialog(parent,kivalasztott);
       szad.setVisible(true);
       if(szad.isMentes()){
           Szemely menteni = szad.getSzemely();
           try {
               model.updateSzemely(menteni);
               listafrissit(); 
           } catch (SQLException ex) {
              MainWindow.HibaAblak(parent, ex.toString());
           }
       }
             }
      else{
          MainWindow.HibaAblak(parent, "To edit a costumer, choose  acostumer!");
      }
    }//GEN-LAST:event_btModositActionPerformed

    private void btTorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTorolActionPerformed
      Szemely kivalasztott= (Szemely) listlSzemelyek.getSelectedValue();
      if(kivalasztott!=null){
          try {
              if(model.getAllRendeles(kivalasztott).size()==0){
                 int valasz=  JOptionPane.showConfirmDialog(parent, "Are you sure you want to delete the costumer?","Delete costumer",JOptionPane.YES_NO_OPTION);
              if(valasz==JOptionPane.YES_OPTION) {
                 
                      
                      model.removeSzemely(kivalasztott);
                      listafrissit();
              }}else{
                    MainWindow.HibaAblak(parent, kivalasztott.getNev()+" has orders, please delete these orders first!");
              }
                  } catch (SQLException ex) {
                      MainWindow.HibaAblak(parent, ex.toString());
                 
              }
              
}else{
          MainWindow.HibaAblak(parent, "To delete a costumer, choose a costumer!");
      }
    
      
    }//GEN-LAST:event_btTorolActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btOkActionPerformed

    /**
     * @param args the command line arguments
     */
  public void listafrissit(){
      if(model!=null){
          try {
              szemelyek=model.getAllSzemely();
              listlSzemelyek.setListData(szemelyek.toArray());
          } catch (SQLException ex) {
             MainWindow.HibaAblak(parent, ex.toString());
          }
      }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btModosit;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btTorol;
    private javax.swing.JButton btUj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listlSzemelyek;
    // End of variables declaration//GEN-END:variables
}
